[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
weight = 20

[[main]]
pre = "github"
url = "https://github.com/guidoos"
identifier = "SK0SEecCnp"
weight = 30

[[footer]]
none = "none"
